# Permalinks
permalink:           pretty

# Setup
title:               It's my (Andrea Hylant's) Blog!
tagline:             A Data Science Blog
url:                 http://ahylant.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrea Hylant
  url:               https://www.linkedin.com/in/andreahylant/
  email:             hylant.andrea@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ahylant

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
